spring.application.name=ms-tiendas
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3307/ms_tiendas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=c2VjcmV0b011eUZ1ZXJ0ZVBhcmFDYXJkTGlua1Byb3llY3RvRHVvYzIwMjY=
jwt.expiration=86400000

ms-login.url=http://localhost:8081
ms-inventario.url=http://localhost:8085
ms-localizacion.url=http://localhost:8086