server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ms-tiendas
  datasource:
    url: jdbc:mysql://localhost:3307/ms_tiendas?createDatabaseIfNotExist=true
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: c2VjcmV0b011eUZ1ZXJ0ZVBhcmFDYXJkTGlua1Byb3llY3RvRHVvYzIwMjY=
  expiration: 86400000

ms-login:
  url: http://localhost:8081

ms-inventario:
  url: http://localhost:8085

ms-localizacion:
  url: http://localhost:8086